title: Hui Yang's Homepage
page-top-title: Hui Yang
top-section-bg-text: International Chinese Language Education
home-subtitle: Hui Yang&ensp;|&ensp;杨卉
copyright-text: '&copy; Hui Yang 2025-2028. All Rights Reserved.'
