title: Jianjun Xia's Homepage
page-top-title: Jianjun Xia
top-section-bg-text: Computer Science
home-subtitle: Jianjun Xia&ensp;|&ensp;夏建军
copyright-text: '&copy; Jianjun Xia 2022-2026. All Rights Reserved.'
